config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'
  resources :posts
  devise_for :users
  resources :users, only: [:show] do
    resources :comments, only: [:edit, :update, :index, :create, :destroy]
  end

  #######ROUTES FOR SORTING AND SEARCH FEATURES############


  post '/posts/time', to: 'posts#time'
  post '/posts/find_author', to: 'posts#find_author'
  post '/comments/find', to: 'comments#find'

  get 'search', to: 'posts#search'
  get 'category/:id', to: 'categories#category', as: 'category'
  get '/users/:id/profile', to: 'sessions#profile', as: 'user_profile'
  get '/auth/facebook/callback' => 'sessions#create'

  get 'sort_newest', to: 'posts#sort_newest'
  get 'sort_oldest', to: 'posts#sort_oldest'
  get 'sort_most', to: 'posts#sort_most'
  get 'sort_least', to: 'posts#sort_least'

  get 'upvote/:id', to: 'posts#upvote'
  get 'downvote/:id', to: 'posts#downvote'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :post_categories
  has_many :posts, through: :post_categories
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :post_categories
  has_many :categories, through: :post_categories, dependent: :nullify
  has_many :comments
  has_many :users, through: :comments

  def categories_attributes=(cat_attr)
    if cat_attr.values != ''
      cat_attr.values.each do |category|
        new_category = Category.find_or_create_by(category)
        self.categories << new_category
      end
    end
  end

  def self.search(params)
    all.where("content LIKE ?", "%#{params}%")
  end
end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base
  belongs_to :post
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :comments
  has_many :posts, through: :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include PostsHelper
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def search
    @posts = Post.search(params[:search])
    render json: @posts
  end

  def sort_newest
    @posts = Post.all.order('created_at DESC')
    render json: @posts
  end

  def sort_oldest
    @posts = Post.all.order('created_at ASC')
    render json: @posts
  end

  def sort_most
    @posts = Post.all.sort {|a,b| b.comments.count <=> a.comments.count}
    render json: @posts
  end

  def sort_least
    @posts = Post.all.sort {|a,b| a.comments.count <=> b.comments.count}
    render json: @posts
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def category
    @category = Category.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  include PostsHelper
  before_action :set_comment, only: [:destroy]

  def index
    @comments = Comment.where(user_id: params[:user_id])

    post = []
    @comments.each do |comment|
      post << Post.find(comment.author_id)
    end
    @post = post.uniq
  end

  def create
    @comment = Comment.create!(comment_params)
    flash[:alert] = "New comment created successfully."
    render json: @comment
  end

  def edit
    @comments = Comment.where(user_id: current_user.id, post_id: params[:post_id])
  end

  def update
    @comment = Comment.find(params[:comment][:id])
    @comment.update(content: params[:comment][:content])
    flash[:alert] = "Comment updated successfully."
    redirect_to post_path(@comment.post_id)
  end

  def destroy
    @comment.destroy
    @comment.save
    flash[:alert] = "Comment destroyed successfully."
    redirect_to user_profile_path
  end

  #finds all comments for a specific post on post#show
  def find
    @comments = Comment.where({post_id: params["id"]})
    render json: @comments
  end

  private
  def comment_params
    params.require(:comment).permit(:content, :user_id, :post_id, :author_id)
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include PostsHelper
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :set_user, only: [:edit]

  def index
    @posts = Post.all

    respond_to do |f|
      f.html { render :index }
      f.json { render json: @posts }
    end
  end

  def new
    @post = Post.new
    @user = current_user
  end

  def create
    @post = Post.create!(post_params)
    flash[:alert] = "New post created successfully."
    redirect_to root_path
  end

  def show
    @comment = Comment.new
  end

  def edit
  end

  def update
    @post.update(post_params)
    flash[:alert] = "Post edited successfully."
    redirect_to root_path
  end

  def destroy
    @post.destroy.save
    @post.comments.each do |comment|
      comment.destroy.save
    end
    flash[:alert] = "Post & Comments destroyed successfully."
    redirect_to user_profile_path
  end

  def time
    @time = {"time": "#{Date.parse(params["time"]).strftime("%A, %b %d")}"}
    render json: @time
  end

  def find_author
    found_author = User.find(params["author"])
    @author = {"author": "#{found_author["email"]}"}
    render json: @author
  end

  def upvote
    @post = Post.find(params["id"])
    @post.vote += 1
    @post.save
    render json: @post
  end

  def downvote
    @post = Post.find(params["id"])
    @post.vote -= 1
    @post.save
    render json: @post
  end

  private
  def post_params
    params.require(:post).permit(:title, :content, :author_id, :category_ids, categories_attributes: [:title])
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def set_user
    @user = User.find(session[:user_id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_or_create_by!(:uid => auth['uid']) do |u|
      u.email = auth['info']['email']
      u.password = SecureRandom.hex
    end
    sign_in(:user, user)
    session[:user_id] = user.id
    redirect_to :root
  end

  def auth
    request.env['omniauth.auth']
  end

  def profile
    if current_user
      @user = current_user
      @posts = Post.where(author_id: @user.id)
    else
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def author_of_post_email(post)
    if user = User.find_by(id: post.author_id)
      user.email
    end
  end

  def author_of_post_id(post)
    if user = User.find_by(id: post.author_id)
      user.id
    end
  end

  def unique_category
    category_arr = []

    Post.all.each do |post|
      post.categories.each do |category|
        if category != ""
          category_arr << category
        end
      end
    end

    category_arr.uniq
  end
end

app/views/categories/category.html.erb
<div align="center">
  <strong><%= @category.title %></strong>
</div>

<hr>

<% @category.posts.each do |post| %>
<div class='well'>
  <strong><%= link_to post.title, post_path(post) %></strong><br>
  <%= post.content %><br>
  <%= post.comments.count %> Comments  |
  <%= author_of_post_email(post) %>  |
  <%= post.created_at.strftime("%A, %b %d") %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<% @comments.each do |comment| %>
<div class="well wellwidth">
  <%= form_for comment, url: user_comment_path(user_id: params[:user_id]), method: 'patch' do |f| %>
    <%= f.text_field :content%>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.hidden_field :post_id, value: comment.post.id %>
    <%= f.hidden_field :id, value: comment.id %>
    <%= f.submit 'Edit Comment', class: 'btn btn-default' %>
    <%= button_to 'Delete Comment', user_comment_path(user_id: params[:user_id]), method: 'delete', class: 'btn btn-default' %>
  <% end %>
</div><br>
<% end %>

app/views/comments/index.html.erb
<div class='well'>
  <% @post.each do |post| %>
    <strong><%= link_to post.title, post_path(post) %></strong><br>
  <%= post.content %><br>
  <% post.categories.each do |category| %>
    <% if category.title != "" %>
      <%= link_to category.title, category_path(category) %>  |
    <% end %>
  <% end %>
  <%= author_of_post_email(post) %><br><br>

    <% @comments.each do |comment| %>
      <% if comment.post_id == post.id %>
        <%= comment.content %>
        <%= link_to 'Edit Comment', edit_user_comment_path(user_id: params[:user_id], id: comment[:id], post_id: post.id)%><br><br>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/layouts/_messages.html.erb
<div>
  <% if flash[:error] %>
    <div class="well alert alert-danger validation">
      <%= content_tag(:div, flash[:error], :id => "flash_error") %>
    </div>
  <% end %>
</div>

<div>
  <% if flash[:notice] %>
    <div class="well alert alert-danger validation">
      <%= content_tag(:div, flash[:notice], :id => "flash_notice") %>
    </div>
  <% end %>
</div>

<div>
  <% if flash[:alert] %>
    <div class="well alert alert-danger validation">
      <%= content_tag(:div, flash[:alert], :id => "flash_alert") %>
    </div>
  <% end %>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand logo" href="/" onclick="window.location.reload()">Hipster Reddit</a>
    </div>

    <ul class='nav navbar-nav navbar-inverse'>
      <% if user_signed_in? %>
        <li><%= link_to current_user.email, user_profile_path(current_user) %></li>
        <li><%= link_to "SIGN OUT", destroy_user_session_path, method: 'delete' %></li>
      <% else %>
          <li><%= link_to "SIGN UP", new_user_registration_path %></li>
          <li><%= link_to "SIGN IN", new_user_session_path %></li>
          <li><%= link_to "SIGN IN WITH FACEBOOK", "/auth/facebook" %></li>
      <% end %>
    </ul>

    <ul class="nav navbar-nav right">
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"><span class="glyphicon glyphicon-sort-by-attributes"></span>
</a>
        <ul class="dropdown-menu">
          <li class="dropdown-header">Sort Posts</li>
          <li><%= link_to "By Newest", 'sort_newest', method: 'get', id: 'sort_newest', remote: true %></li>
          <li><%= link_to "By Oldest", 'sort_oldest', method: 'get', id: 'sort_oldest', remote: true %></li>
          <li role="separator" class="divider"></li>
          <li class="dropdown-header">Sort Comments</li>
          <li><%= link_to "By Most", 'sort_most', method: 'get', id: 'sort_most', remote: true %></li>
          <li><%= link_to "By Least", 'sort_least', method: 'get', id: 'sort_least', remote: true %></li>
        </ul>
      </li>
    </ul>

    <div class="navbar-form pull-right">
      <div class="form-group">
        <%= form_tag search_path, method: "get", id: 'search_form', remote: true do %>
          <%= text_field_tag "search" %>
        <%= submit_tag 'Search Posts', class: 'btn btn-primary btn-sm' %>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hipster Reddit</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='https://fonts.googleapis.com/css?family=Quicksand:700|Roboto' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/nav' %><br>
<%= render 'layouts/messages' %><br>
<div class='container'>
  <%= yield %>
</div>


</body>
</html>

app/views/posts/_form.html.erb
<div class='well form-group newpost'>
  <%= form_for @post do |f| %>
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control' %><br>
    <%= f.label :content %><br>
    <%= f.text_area :content, class: 'form-control' %><br>
    <%= f.collection_select :category_ids, Category.all, :id, :title, prompt: "Choose a Category" %><br><br>
    Or create your own category: <br>
    <%= f.fields_for :categories, @post.categories.build do |field| %>
      <%= field.text_field :title, class: 'form-control' %><br>
    <% end %>
    <%= f.hidden_field :author_id, value: @user.id %>
    <%= f.submit 'Submit Post', class: 'btn btn-default' %>
  <% end %>
</div>

app/views/posts/edit.html.erb
<%= render 'form' %>

app/views/posts/index.html.erb
<ul class="nav nav-tabs nav-justified" id="index_categories"></ul>
<div class='posts'></div>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<% if user_signed_in? && current_user.id == @post.author_id %>
  <%= link_to 'EDIT POST', edit_post_path(@post) %><br>
  <%= link_to 'DELETE POST', post_path(@post), method: 'delete' %><br>
<% end %><br>


<div class='well'>
  <strong><%= link_to @post.title, post_path(@post) %></strong><br>
  <%= @post.content %><br>
  <% @post.categories.each do |category| %>
    <% if category.title != "" %>
      <%= link_to category.title, category_path(category) %>  |
    <% end %>
  <% end %>
  <%= author_of_post_email(@post) %><br><br>

  COMMENTS: <br>
  <div id="comment_ajax"></div>
</div>

<% if current_user %>
  <%= form_for @comment, url: user_comments_path(params[:id]), id: 'new_comment', remote: true do |f| %>
    <%= f.text_field :content, id: :content %>
    <%= f.hidden_field :user_id, value: current_user.id, id: :user_id %>
    <%= f.hidden_field :post_id, value: @post.id, id: :post_id %>
    <%= f.hidden_field :author_id, value: params[:id], id: :author_id %>
    <%= f.submit %>
  <% end %>
<% end %>

<script type="text/javascript" charset="utf-8">
//RETURNS ALL COMMENTS FOR POST/:ID, APPENDS TO #COMMENT_AJAX
  $.post('/comments/find', {'id': <%= @post.id %>}).success(function(response) {
    var comments = response["comments"];
    comments.forEach(function(comment) {
      $("#comment_ajax").append(comment["content"] + '<br>');
    });
  });

  //SUBMITS NEW COMMENT FORM, ADDS TO #COMMENT_AJAX DIV
  $('form').submit(function(event) {
    event.preventDefault();
    var content = $("#content").val();
    var comment = $(this).serialize();
    <% if current_user %>
    $.post('/users/' + <%= current_user.id %> + '/comments', comment).success(function(data) {
      $("#comment_ajax").append(content + '<br>');
      $('form').each(function() {
        this.reset();
      })
    });
    <% end %>
  return false;
  });
</script>